#!/usr/bin/env lua

-- NOTE: If sketchybar appears broken (missing time, date, front_app), use
-- `sketchybar --reload` instead of killing the process. When killed, the Lua
-- event loop doesn't reinitialize properly - items appear but callbacks never
-- fire to populate them.

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath
	.. ";/Users/"
	.. os.getenv("USER")
	.. "/.local/share/sketchybar_lua/sketchybar.so"

-- Require the sketchybar module
Sbar = require("sketchybar")

-- Specify which bar (only necessary if not default: sketchybar)
Sbar.set_bar_name("sketchybar")

-- Load the init.lua file
Sbar.begin_config()
require("init")
Sbar.hotload(true)
Sbar.end_config()

-- Load helper scripts
os.execute("killall weather-updater")
os.execute(os.getenv("HOME") .. "/.config/sketchybar/plugins/weather-updater &")

-- Run the event loop of the sketchybar module (without this there will be no
-- bi-directional communication between the lua module and sketchybar)
Sbar.event_loop()
