local M = {}

function M.build(data)
  local p = data.palette
  local r = data.roles

  return {
    Normal = { fg = r.ui.fg, bg = r.ui.bg },
    NormalNC = { fg = r.ui.fg, bg = r.ui.bg },
    NormalFloat = { fg = r.ui.fg, bg = r.ui.float },
    FloatBorder = { fg = r.ui.border, bg = r.ui.float },
    FloatTitle = { fg = r.syntax.keyword, bg = r.ui.float, bold = true },
    SignColumn = { bg = r.ui.bg },
    LineNr = { fg = p.gutter, bg = r.ui.bg },
    CursorLine = { bg = r.ui.cursorline },
    CursorLineNr = { fg = r.syntax.type, bg = r.ui.cursorline, bold = true },
    CursorColumn = { bg = r.ui.cursorline },
    ColorColumn = { bg = r.ui.bg_alt },
    EndOfBuffer = { fg = r.ui.bg },
    VertSplit = { fg = r.ui.border, bg = r.ui.bg },
    WinSeparator = { fg = r.ui.border, bg = r.ui.bg },
    Folded = { fg = r.ui.muted, bg = r.ui.bg_alt },
    FoldColumn = { fg = r.ui.muted, bg = r.ui.bg },
    Visual = { bg = r.ui.selection },
    VisualNOS = { bg = r.ui.selection },
    Search = { fg = r.ui.fg, bg = r.ui.search },
    CurSearch = { fg = r.ui.bg, bg = r.ui.inc_search, bold = true },
    IncSearch = { fg = r.ui.bg, bg = r.ui.inc_search, bold = true },
    MatchParen = { fg = r.syntax.keyword, bold = true },
    Pmenu = { fg = r.ui.fg, bg = r.ui.pmenu },
    PmenuSel = { fg = r.ui.fg, bg = r.ui.pmenu_sel, bold = true },
    PmenuSbar = { bg = r.ui.bg_alt },
    PmenuThumb = { bg = r.ui.border },
    StatusLine = { fg = r.ui.fg, bg = r.ui.bg_alt },
    StatusLineNC = { fg = r.ui.muted, bg = r.ui.bg_alt },
    TabLine = { fg = r.ui.muted, bg = r.ui.bg_alt },
    TabLineFill = { bg = r.ui.bg_alt },
    TabLineSel = { fg = r.ui.fg, bg = r.ui.cursorline, bold = true },
    Directory = { fg = p.blue },
    Title = { fg = r.syntax.keyword, bold = true },
    ErrorMsg = { fg = r.diagnostics.error },
    WarningMsg = { fg = r.diagnostics.warn },
    MoreMsg = { fg = r.diagnostics.info },
    Question = { fg = r.diagnostics.hint },
    Conceal = { fg = r.ui.muted },
    NonText = { fg = r.ui.border },
    SpecialKey = { fg = r.ui.border },
    Whitespace = { fg = r.ui.border },
    Comment = { fg = r.syntax.comment, italic = true },
    Constant = { fg = r.syntax.constant },
    String = { fg = r.syntax.string },
    Character = { fg = r.syntax.string },
    Number = { fg = r.syntax.number },
    Boolean = { fg = r.syntax.constant },
    Float = { fg = r.syntax.number },
    Identifier = { fg = r.syntax.variable },
    Function = { fg = r.syntax["function"] },
    Statement = { fg = r.syntax.keyword },
    Conditional = { fg = r.syntax.keyword },
    Repeat = { fg = r.syntax.keyword },
    Label = { fg = r.syntax.keyword },
    Operator = { fg = r.syntax.operator },
    Keyword = { fg = r.syntax.keyword },
    Exception = { fg = r.syntax.keyword },
    PreProc = { fg = r.syntax.preproc },
    Include = { fg = r.syntax.keyword },
    Define = { fg = r.syntax.preproc },
    Macro = { fg = r.syntax.preproc },
    PreCondit = { fg = r.syntax.preproc },
    Type = { fg = r.syntax.type },
    StorageClass = { fg = r.syntax.type },
    Structure = { fg = r.syntax.type },
    Typedef = { fg = r.syntax.type },
    Special = { fg = r.syntax.property },
    SpecialComment = { fg = r.syntax.comment, italic = true },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Error = { fg = r.diagnostics.error },
    Todo = { fg = r.ui.bg, bg = r.diagnostics.warn, bold = true },
    DiagnosticError = { fg = r.diagnostics.error },
    DiagnosticWarn = { fg = r.diagnostics.warn },
    DiagnosticInfo = { fg = r.diagnostics.info },
    DiagnosticHint = { fg = r.diagnostics.hint },
    DiagnosticOk = { fg = r.diagnostics.ok },
    DiagnosticVirtualTextError = { fg = r.diagnostics.error, bg = r.diff.delete_bg },
    DiagnosticVirtualTextWarn = { fg = r.diagnostics.warn, bg = r.diff.change_bg },
    DiagnosticVirtualTextInfo = { fg = r.diagnostics.info, bg = r.diff.change_bg },
    DiagnosticVirtualTextHint = { fg = r.diagnostics.hint, bg = r.diff.add_bg },
    DiagnosticUnderlineError = { undercurl = true, sp = r.diagnostics.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = r.diagnostics.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = r.diagnostics.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = r.diagnostics.hint },
    DiffAdd = { bg = r.diff.add_bg },
    DiffChange = { bg = r.diff.change_bg },
    DiffDelete = { fg = r.vcs.removed, bg = r.diff.delete_bg },
    DiffText = { bg = r.diff.text_bg },
    Added = { fg = r.vcs.added },
    Changed = { fg = r.vcs.changed },
    Removed = { fg = r.vcs.removed },
    GitSignsAdd = { fg = r.vcs.added, bg = r.ui.bg },
    GitSignsChange = { fg = r.vcs.changed, bg = r.ui.bg },
    GitSignsDelete = { fg = r.vcs.removed, bg = r.ui.bg },
    SnacksPicker = { fg = r.ui.fg, bg = r.ui.bg },
    SnacksPickerBorder = { fg = r.ui.border, bg = r.ui.bg },
    SnacksPickerTitle = { fg = r.syntax.keyword, bg = r.ui.bg, bold = true },
    SnacksPickerDir = { fg = r.ui.muted },
    BlinkCmpMenu = { fg = r.ui.fg, bg = r.ui.pmenu },
    BlinkCmpMenuBorder = { fg = r.ui.border, bg = r.ui.pmenu },
    BlinkCmpLabel = { fg = r.ui.fg },
    BlinkCmpLabelMatch = { fg = r.syntax.keyword, bold = true },
    BlinkCmpKind = { fg = r.syntax.type },
    BlinkCmpDoc = { fg = r.ui.fg, bg = r.ui.float },
    BlinkCmpDocBorder = { fg = r.ui.border, bg = r.ui.float },
    BlinkCmpSignatureHelp = { fg = r.ui.fg, bg = r.ui.float },
    BlinkCmpSignatureHelpBorder = { fg = r.ui.border, bg = r.ui.float },
    NoiceCmdlinePopup = { fg = r.ui.fg, bg = r.ui.float },
    NoiceCmdlinePopupBorder = { fg = r.ui.border, bg = r.ui.float },
    NoicePopup = { fg = r.ui.fg, bg = r.ui.float },
    NoicePopupBorder = { fg = r.ui.border, bg = r.ui.float },
    WhichKey = { fg = r.syntax.keyword },
    WhichKeyGroup = { fg = r.syntax.type },
    WhichKeyDesc = { fg = r.syntax["function"] },
    WhichKeySeparator = { fg = r.ui.muted },
    WhichKeyBorder = { fg = r.ui.border },
    TelescopeNormal = { fg = r.ui.fg, bg = r.ui.float },
    TelescopeBorder = { fg = r.ui.border, bg = r.ui.float },
    TelescopeTitle = { fg = r.syntax.keyword, bg = r.ui.float, bold = true },
    TelescopeSelection = { bg = r.ui.cursorline },
    ["@comment"] = { link = "Comment" },
    ["@constant"] = { link = "Constant" },
    ["@string"] = { link = "String" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@operator"] = { link = "Operator" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = r.syntax.builtin },
    ["@function.method"] = { link = "Function" },
    ["@constructor"] = { fg = r.syntax.type },
    ["@parameter"] = { fg = r.syntax.parameter },
    ["@property"] = { fg = r.syntax.property },
    ["@field"] = { fg = r.syntax.property },
    ["@variable"] = { fg = r.syntax.variable },
    ["@variable.builtin"] = { fg = r.syntax.builtin },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = r.syntax.builtin },
    ["@module"] = { fg = r.syntax.type },
    ["@punctuation.delimiter"] = { fg = r.syntax.operator },
    ["@punctuation.bracket"] = { fg = r.ui.fg },
    ["@markup.heading"] = { fg = r.syntax.keyword, bold = true },
    ["@markup.link"] = { fg = r.diagnostics.info, underline = true },
    ["@tag"] = { fg = r.syntax.keyword },
    ["@tag.attribute"] = { fg = r.syntax.property },
  }
end

return M
