return {
	{ "akinsho/bufferline.nvim", enabled = false },
	{ "catppuccin/nvim", enabled = false },
	{ "echasnovski/mini.pairs", enabled = false },
	{ "folke/persistence.nvim", enabled = false },
	{ "echasnovski/mini.ai", enabled = false },
	{ "garymjr/nvim-snippets", enabled = false },
	{ "goolord/alpha-nvim", enabled = false },
	{ "iamcco/markdown-preview.nvim", enabled = false },
	{ "jesseduffield/lazygit", enabled = false },
	{ "lewis6991/gitsigns.nvim", enabled = false },
	{ "nvim-lualine/lualine.nvim", enabled = false },
	{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "nvimdev/dashboard-nvim", enabled = false },
	{ "rafamadriz/friendly-snippets", enabled = false },
	{ "ibhagwan/fzf-lua", enabled = false },
}
