[env]
ANTHROPIC_API_KEY = { value = "", tools = false }
OPENAI_API_KEY = { value = "", tools = false }
OPENROUTER_API_KEY = { value = "", tools = false }
PI_CODING_AGENT_DIR = "{{env.HOME}}/.config/pi-work"
CLAUDE_CONFIG_DIR = "{{env.HOME}}/.config/claude-gmatter"
