-- require("items.apple")
-- require("items.spaces")
-- require("items.front_app")
require("items.left_bracket")
require("items.right_bracket")

require("items.time")
require("items.date")
require("items.weather")
require("items.cpu")
-- require("items.uname")
-- require("items.volume")
-- require("items.battery")
-- require("items.media")
