#! /usr/bin/env bash

# 'active_color=gradient(top_left=0xff82aaff,bottom_right=0xffc3e88d))' \
# 'active_color=glow(0xff82aaff)' \

borders \
	'active_color=glow(0xff82aaff)' \
	inactive_color=0x00000000 \
	width=6.0 \
	hidpi=on
